"""Create solar panels table

Revision ID: a546bf298313
Revises: 
Create Date: 2026-08-16 01:15:44.339163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a546bf298313'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('string_id', sa.String(length=50), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('efficiency_loss', sa.Float(), nullable=False),
    sa.Column('power_output_kw', sa.Float(), nullable=False),
    sa.Column('heatmap_matrix', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('string_id', sa.String(length=50), nullable=False),
    sa.Column('panel_id', sa.String(length=50), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('irradiance', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_telemetry_panel_id'), 'panel_telemetry', ['panel_id'], unique=False)
    op.create_index(op.f('ix_panel_telemetry_string_id'), 'panel_telemetry', ['string_id'], unique=False)
    op.create_index(op.f('ix_panel_telemetry_timestamp'), 'panel_telemetry', ['timestamp'], unique=False)
    op.create_table('solar_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity_kw', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_panels_id'), 'solar_panels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_panels_id'), table_name='solar_panels')
    op.drop_table('solar_panels')
    op.drop_index(op.f('ix_panel_telemetry_timestamp'), table_name='panel_telemetry')
    op.drop_index(op.f('ix_panel_telemetry_string_id'), table_name='panel_telemetry')
    op.drop_index(op.f('ix_panel_telemetry_panel_id'), table_name='panel_telemetry')
    op.drop_table('panel_telemetry')
    op.drop_table('diagnostic_reports')
    # ### end Alembic commands ###
